### PR TITLE
fix client port now changing in package.json and removing one time use variables noticed

### PR DESCRIPTION
**Pull request by subtosharki**
## Bug

- [ ] Related issues linked using `closes: #number`

## Feature

- [ ] Related issues linked using `closes: #number`
- [ ] There is only 1 db migration with no breaking changes.

## Translations

- [ ] `.json` files are formatted: `yarn format`
- [ ] Translations are correct
- [ ] New translation? It's been added to `next.config.js`

### CODE REVIEW

**Comment by subtosharki** [comment]
no idea why the other stuff was there, it works fine how it is in the fix now

**Comment by Dev-CasperTheGhost** [comment]
I'm not sure on this one. I'll need to take a look myself to be 100% sure this fixes it **on all platforms**

**Comment by Dev-CasperTheGhost** [comment]
@subtosharki I'm going to close this PR since it works fine without these changing. Can you provide more information about what is not working here?

**Comment by subtosharki** [comment]
i logged the dir, its going to the package.json in the root folder, not /packages/client/package.json

**Comment by Dev-CasperTheGhost** [comment]
should be fixed now.

**Pull request closed without merging**
