### PR TITLE
Add sergeant role (second LEO supervisor)

### LINKED ISSUE #1922: Add Permission: Change Officer Rank
### Describe the feature

Could we have a permission added for changing a unit rank?

I don't mean the Admin permission to create new ranks in the CAD.
I just mean a single permission to update Officer Ranks for a unit in a department.
Such as for Supervisors etc. So they can update someones rank when they get promoted or demoted.

### Additional Context

Right now the only way to do that is through Manage Units which is way more risky to grant. People can then delete peoples units and do anything they want with it. So it would be better if we could just have ability to change someones rank only.

### PR DESCRIPTION
**Pull request by glxgxr**
## Feature

- [x] Related issues linked using `closes: #number`
- [x] There is only 1 db migration with no breaking changes.

## Translations

- [x] `.json` files are formatted: `pnpm format`
- [x] Translations are correct
- [x] New translation? It's been added to `i18n.config.mjs`

closes #1922

### CODE REVIEW

**Comment by casperiv0** [comment]
Nice PR, though, what's the point if they can use custom roles instead 👀?

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Nice PR, though, what's the point if they can use custom roles instead 👀?

I'm wondering if this is related to permissions.
https://github.com/SnailyCAD/snaily-cadv4/issues/1922

The need for another Supervisor option is important for lower level Supervisor so they don't have as much power. (In case someone gets terminated from a Department and then tries to sabotage officers)

**Comment by jxckUK** [comment]
So ultimately another role isn't whats needed (as this can be achieved with custom roles), but additional permission keys so you can split out the "Manage Units" key into less privileged tasks such as the ones you listed?

> Manage another Officer's Rank
> Manage another Officer's Callsign

**Comment by Legacy-TacticalGamingInteractive** [comment]
Yes exactly

Basically so we can fine tune a few more permissions as needed for security reasons

**Comment by Legacy-TacticalGamingInteractive** [comment]
Does this one just need to be merged with next update then its good to go basically?

**Comment by jxckUK** [comment]
I don't think this PR is effective in resolving the issue raised, we need additional permission keys, not more static roles that people can replicate already with custom roles.

Perhaps something Casper can comment on this and potentially look to add more segregation to the manage unit permissions.

**Comment by Legacy-TacticalGamingInteractive** [comment]
I also realized just now that Manage Officer Rank (to change an officer's rank) is not an option under Custom Roles as a Permission to select.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Nice PR, though, what's the point if they can use custom roles instead 👀?

I think we can close this one now because this method is easier now: https://github.com/SnailyCAD/snaily-cadv4/pull/1956

**Comment by casperiv0** [comment]
Superseded by #1956

**Pull request closed without merging**
