### PR TITLE
Manage unit rank role

### PR DESCRIPTION
**Pull request by tugamars**
## Feature

- [x] Related issues linked using
- [x] There is only 1 db migration with no breaking changes.

closes: #1954

### CODE REVIEW

**Comment by Legacy-TacticalGamingInteractive** [comment]
@WhitigolProd possible to merge?

**Comment by Legacy-TacticalGamingInteractive** [comment]
@casperiv0 does this one look good?

**Review by casperiv0 — APPROVED** [review]
Looks fine to me! Has this been tested?

**Comment by tugamars** [comment]
Yes, it has been tested in local environment.

A segunda, 16/09/2024, 08:02, Casper Iversen ***@***.***>
escreveu:

**Pull request merged**
