### PR TITLE
:tada: feat: set units off-duty on logout

### PR DESCRIPTION
**Pull request by Dev-CasperTheGhost**
## Bug

- [ ] Related issues linked using `closes: #number`

## Feature

- [x] Related issues linked using closes: #339 
- [x] There is only 1 db migration with no breaking changes.

## Translations

- [ ] `.json` files are formatted: `yarn format`
- [ ] Translations are correct
- [ ] New translation? It's been added to `next.config.js`

### CODE REVIEW

**Comment by ViolentMinds** [comment]
I hope this works soon. Because we have like 40 officers who are still "on duty" lol. They never go Off Duty when they leave. 
Alternatively we should get an option to "Select All" on the Manage Units page I think that would help rather than having to click each one of them to set them off duty.

**Comment by Dev-CasperTheGhost** [comment]
> Alternatively we should get an option to "Select All" on the Manage Units page I think that would help rather than having to click each one of them to set them off duty.

Yeah, sure! I will make a feature request for this!

**Comment by Dev-CasperTheGhost** [comment]
> I hope this works soon. Because we have like 40 officers who are still "on duty" lol. They never go Off Duty when they leave.

You mention you have 40 officers who are on-duty, just a quick question: How's the performance of this? Is the UI laggy, do you think there's room for improvements? I'd love to know!

@ViolentMinds

**Comment by ViolentMinds** [comment]
Its not laggy for me. Runs fine. :)

-------

The manage units page could use some format fixing though.
See how the Manage button is off the screen.

A) Make each user to be 2 rows instead of one so you can fit more on the screen.
You can place the Manage button below their Officer name and some other colums into the new row.

B) You remove the Manage button and you make the Officer Name become a link to Manage instead. So instead of clicking on Manage the admin can just click on the name. For example in my screenshot, "Alice" could the the link for Manage.

image


Its not really that big of a deal though. People can scroll to the right. Just ideas.

**Pull request merged**
